Improved if condition for reboot and captured shutdown output

diff --git a/auter b/auter
--- a/auter
+++ b/auter
@@ -152,11 +152,12 @@ function reboot_server() {
   fi
 
   logit "INFO: Rebooting server"
-  if [[ ${NOWALLMSG} ]] && shutdown --help | grep -q "no-wall"; then
-    /sbin/shutdown --no-wall -r +2 "auter: System reboot to apply updates" &>/dev/null &
+  if [[ ${NOWALLMSG} -eq 1 ]] && shutdown --help | grep -q "no-wall"; then
+    SHUTDOWNOUTPUT=$(/sbin/shutdown --no-wall -r +2 "auter: System reboot to apply updates" &)
   else
-    /sbin/shutdown -r +2 "auter: System reboot to apply updates" &
+    SHUTDOWNOUTPUT=$(/sbin/shutdown -r +2 "auter: System reboot to apply updates" &)
   fi
+  [[ $? -ne 0 ]] && logit "ERROR: ${SHUTDOWNOUTPUT}"
 }
 
 function post_reboot() {
